apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: k8s-test-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /opt/k8s-data/redis
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: k8s-test-env
spec:
  selector:
    app: redis
  ports:
    - port: 6378
      targetPort: 6379
      nodePort: 16378  # 宿主机访问端口
  type: NodePort
